apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluss.fullname" . }}-coordinator
  labels:
    app: {{ include "fluss.name" . }}
    component: coordinator
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.coordinator.service.port }}
      targetPort: {{ .Values.coordinator.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "fluss.name" . }}
    component: coordinator 