{{- if .Values.usePersistence }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluss.fullname" . }}-minio-secret
  labels:
    app: {{ include "fluss.name" . }}
    component: minio
type: Opaque
# Use stringData so the values are automatically base64 encoded by Kubernetes
stringData:
  accessKey: {{ .Values.minio.credentials.accessKey | quote }}
  secretKey: {{ .Values.minio.credentials.secretKey | quote }}
{{- end }} 