apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluss.fullname" . }}-tablet
  labels:
    app: {{ include "fluss.name" . }}
    component: tablet
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.tablet.service.port }}
      targetPort: {{ .Values.tablet.service.port }}
      protocol: TCP
      name: rpc
  selector:
    app: {{ include "fluss.name" . }}
    component: tablet 